In [77]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set()
%matplotlib inline 

In [78]:
from sklearn.linear_model import LinearRegression

In [79]:
data = pd.read_csv('1.02. Multiple linear regression.csv')

In [80]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [81]:
x = data['SAT']
y = data['GPA']

In [82]:
x.shape

(84,)

In [83]:
y.shape

(84,)

In [85]:
x_matrix = x.values.reshape(-1,1) 
y_matrix = y.values.reshape(-1, 1)

In [86]:
reg = LinearRegression()

In [87]:
reg.fit(x_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [88]:
# R-Squared
reg.score(x_matrix, y) 

0.40600391479679765

In [89]:
reg.coef_

array([0.00165569])

In [90]:
reg.intercept_

0.2750402996602803

In [92]:
reg.predict(100)

ValueError: Expected 2D array, got scalar array instead:
array=100.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [93]:
new_data = pd.DataFrame(data=[1740,1760], columns=['SAT'])

In [94]:
new_data

SAT
0  1740
1  1760

In [95]:
reg.predict(new_data)

array([3.15593751, 3.18905127])

In [96]:
new_data['Predicted GPA'] = reg.predict(new_data) 

In [97]:
reg.score(x_matrix,y)

0.40600391479679765

In [98]:
# Feature selection 
from sklearn.feature_selection import f_regression 

In [102]:
f_regression(x_matrix, y)

(array([56.04804786]), array([7.19951844e-11]))

In [ ]:
x.values.reshape(-1,1)

In [104]:
# Creating a summary table 

In [105]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

AttributeError: 'Series' object has no attribute 'columns'

In [106]:
cd 