In [1]:
"this is a string"

'this is a string'

In [2]:
'this is a string'

'this is a string'

In [3]:
"I can't go"

"I can't go"

In [4]:
x = 'hello '

In [5]:
x

'hello '

In [6]:
print(x)


hello 


In [7]:
num = 12
name = 'abcdefghijklmno'

In [8]:
"my number is {} and my name is {}" .format(num,name)

'my number is 12 and my name is abcdefghijklmno'

In [9]:
print("my number is {} and my name is {}" .format(num,name))

my number is 12 and my name is abcdefghijklmno


In [10]:
name[0:]

'abcdefghijklmno'

In [11]:
name[3:7]

'defg'

In [12]:
my_list = ['a','b','c']

my_list.append('d')

In [13]:
my_list.append('d')

In [14]:
my_list

['a', 'b', 'c', 'd']

In [15]:
my_list[0]

'a'

In [16]:
my_list[0:3]

['a', 'b', 'c']

In [17]:
my_list[0] = 'new'

In [18]:
my_list

['new', 'b', 'c', 'd']

In [19]:
new_list = [12,5,6,7,[2,3,7,[9,7,4]]]

In [20]:
print(new_list[4][3][2])

4


In [21]:
dict = {1:'one', 2:'two', 3:'three'}

In [22]:
dict[1]

'one'

In [23]:
dict[2]

'two'

In [24]:
new_dict = {1:"one", 2:'two', 3:['one',2,2,3,['one','two','target']]}

In [25]:
new_dict[3][4][2]

'target'

In [26]:
new_dict = {1:"one", 2:'two', 3:['one',2,2,3,['one','two','target',{'one':'number one', 'two':'number two',}]]}

In [27]:
new_dict[3][4][3]['two']

'number two'

In [28]:
{1,2,3}

{1, 2, 3}

In [29]:
{2,2,3,4,5,6,6,6}

{2, 3, 4, 5, 6}

In [30]:
s = {3,5,6,7}

In [31]:
s.add(8)

In [32]:
s

{3, 5, 6, 7, 8}

In [33]:
s.add(6)

In [34]:
s

{3, 5, 6, 7, 8}

In [35]:
True and True

True

In [36]:
True and False 

False

In [37]:
False and False

False

In [38]:
True and True

True

In [39]:
1 is 1 or 2 > 3

True

In [40]:
1 is 1 and 2>4

False

In [41]:
1 is 1

True

In [42]:
1 is "one"

False

In [43]:
True or True

True

In [44]:
True or False

True

In [45]:
if 1<2:
    print('yes it is true')

yes it is true


In [46]:
if True:
    x = 2+3

In [47]:
x

5

In [48]:
if False:
    x = 2+3

In [49]:
x

5

In [50]:
if 1==4:
    print('one is equal to one')
    
elif 2==6:
    print('two is equal to two')
    
else:
    print('else statement')

else statement


In [51]:
seq = [1,3,4,4,5,6]

In [52]:
for i in seq:
    print(i)

1
3
4
4
5
6


In [53]:
for x in range(1):
    print(x)

0


In [54]:
x = 1

while x < 10:
    print("x is: {} ".format(x))
    x+=1

x is: 1 
x is: 2 
x is: 3 
x is: 4 
x is: 5 
x is: 6 
x is: 7 
x is: 8 
x is: 9 


In [55]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
print('ahsan')

ahsan


In [57]:
tuple(range(10,15))

(10, 11, 12, 13, 14)

In [58]:
list(range(5))


[0, 1, 2, 3, 4]

In [59]:
y = [1,2,3,4]

In [60]:
x

10

In [61]:
# out = []
# for num in x:
#     out.append(num**2)
    

In [62]:
# print(out)

In [63]:
x = [1,2,3,4]

In [64]:
out = []
for item in x:
    out.append(item**2)
print(out)

[1, 4, 9, 16]


In [65]:
[item**2 for item in x]


[1, 4, 9, 16]

In [66]:
seq = [1,2,3,4,5]

In [67]:
list(map(lambda num : num*3, seq))

[3, 6, 9, 12, 15]

In [68]:
filter(lambda num : num % 2 == 0, seq)

In [69]:
list(filter(lambda num:num%2!=0, seq))

[1, 3, 5]

In [70]:
x = [1,3,4,5,'one']

In [71]:
item = x.pop()

In [72]:
item

'one'

In [73]:
x in [1,3,4,5,'one']

False

In [74]:
x in [1,3,4,5,'x']

False

In [75]:
# b in ['b', 'c', 'd']

In [76]:
a = [(1,2,3),(4,5,6),(7,8,9),(1,5,8)]

In [77]:
for b,c,d in a:
    print(c)
    print(d)
    print(b)

2
3
1
5
6
4
8
9
7
5
8
1


In [78]:
list

list

In [79]:
print(list)

<class 'list'>


In [80]:
list = [1, 3, 4, 5, 6]

In [81]:
print(list)

[1, 3, 4, 5, 6]


In [82]:
empty = []

for x in list:
    empty.append(x*2)

In [83]:
print(list)

[1, 3, 4, 5, 6]


In [84]:
print(empty)

[2, 6, 8, 10, 12]


In [85]:
new_list = [ x* 2 for x in list]

In [86]:
print(new_list)

[2, 6, 8, 10, 12]


In [87]:
create_list = [ x * 2 for x in range(0, 10)]

In [88]:
print(create_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [89]:
list_new = [x**2 for x in range(10, 0 , -1)]

In [90]:
list_new

[100, 81, 64, 49, 36, 25, 16, 9, 4, 1]

In [91]:
string = 'This dog runs faster than the other dog dude!'
substring = 'dog'
count = string.count(substring)
print(count)
    

2


In [92]:
def count_string(string):
    sub_string = 'dog'
    count = string.count(substring)
    print(count)
count_string('This dog runs faster than the other dog dude!')
    

    

2


In [93]:
string = "Is there a dog here?"
new_ls = string.split()

In [94]:
print(new_ls)

['Is', 'there', 'a', 'dog', 'here?']


In [95]:
print(filter(lambda x : 'dog' in x, new_ls))

In [96]:
def find_dog(new_ls):
    splt = new_ls.split()
    if 'dog' in splt:
        print("True")
    else:
        print('False')

        
find_dog("Is there a dog here?")


True


In [97]:
new_fl = filter('dog', new_ls)

In [98]:
print

<function print>

In [99]:
# seq = ['soup','dog','salad','cat','great']
# list(filter(lambda word: word[0]=='s',seq))

In [102]:
# print(seq)

In [103]:
res = [k for k in seq if 's' in k]
print(res)

TypeError: argument of type 'int' is not iterable

In [104]:
seq = ['soup','dog','salad','cat','great']
print(list(filter(lambda x : 's' in x, seq )))


TypeError: 'list' object is not callable

In [105]:
list(filter(lambda num:num%2!=0, seq))

TypeError: 'list' object is not callable


*You are driving a little too fast, and a police officer stops you.
Write a function to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket".
If your speed is 60 or less, the result is "No Ticket".
If speed is between 61 and 80 inclusive, the result is "Small Ticket".
If speed is 81 or more, the result is "Big Ticket".
Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- 
on your birthday, your speed can be 5 higher in all cases. *


In [106]:
def speed_test(speed, is_birthday):
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speed > 80 and speed < 70 :
        return 'Big ticket'
    elif speed < 80:
        print('Small Ticket')
    else:
        print('No Ticket')
        
speed_test(33, True)

Small Ticket


In [107]:
speed_test(90, True)

No Ticket


In [108]:
string = ['a', 'long', 'one']
def print_short(string):
    for x in string.len():
        if 
    

SyntaxError: invalid syntax (<ipython-input-108-45436437ea28>, line 4)

In [109]:
random = [1,2,3,4,4,5,67,8,9]
even_list = list(filter(lambda x :( x%2==0 ), random))
print(even_list)

TypeError: 'list' object is not callable

In [110]:

# list of numbers  
list1 = [10, 21, 4, 45, 66, 93, 11]  
  
  
# we can also print even no's using lambda exp.  
even_nos = list(filter(lambda x: (x % 2 == 0), list1)) 
  
print("Even numbers in the list: ", even_nos)

TypeError: 'list' object is not callable

In [111]:
# callable(even_nos)

In [112]:
import numpy as np
my_list = [1,2,3]
print(my_list)
arr = np.array(my_list)
print(arr)

[1, 2, 3]
[1 2 3]


In [113]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [114]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
np.arange(0,11,2)  

array([ 0,  2,  4,  6,  8, 10])

In [116]:
np.zeros(3)

array([0., 0., 0.])

In [117]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [118]:
np.linspace(0,5.100)

array([0.        , 0.10408163, 0.20816327, 0.3122449 , 0.41632653,
       0.52040816, 0.6244898 , 0.72857143, 0.83265306, 0.93673469,
       1.04081633, 1.14489796, 1.24897959, 1.35306122, 1.45714286,
       1.56122449, 1.66530612, 1.76938776, 1.87346939, 1.97755102,
       2.08163265, 2.18571429, 2.28979592, 2.39387755, 2.49795918,
       2.60204082, 2.70612245, 2.81020408, 2.91428571, 3.01836735,
       3.12244898, 3.22653061, 3.33061224, 3.43469388, 3.53877551,
       3.64285714, 3.74693878, 3.85102041, 3.95510204, 4.05918367,
       4.16326531, 4.26734694, 4.37142857, 4.4755102 , 4.57959184,
       4.68367347, 4.7877551 , 4.89183673, 4.99591837, 5.1       ])

In [119]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [120]:
np.random.rand(5)

array([0.14564045, 0.93287646, 0.45990142, 0.96722971, 0.46663909])

In [121]:
np.random.rand(5,5)

array([[0.87993361, 0.07135211, 0.38989197, 0.81987639, 0.64052018],
       [0.98278749, 0.12074932, 0.44810616, 0.10118139, 0.17050845],
       [0.12084443, 0.80953271, 0.2153024 , 0.68945249, 0.85646137],
       [0.24168337, 0.91537005, 0.54880643, 0.39679313, 0.95784268],
       [0.22290031, 0.71232307, 0.18008424, 0.18585951, 0.1978023 ]])

In [122]:
np.random.randn(2)

array([-0.07121841,  1.61209651])

In [123]:
np.random.randint(1,100,10)

array([20, 16, 49, 12,  9, 49, 44, 16, 34, 44])

In [124]:
arr = np.arange(25)

In [125]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [126]:
ranarr = np.random.randint(0,50,10)

In [127]:
ranarr

array([48, 45,  1, 41, 16, 49, 17, 34, 31, 17])

In [128]:
ranarr

array([48, 45,  1, 41, 16, 49, 17, 34, 31, 17])

In [129]:
ranarr.max()

49

In [130]:
ranarr.min()

1

In [131]:
ranarr.argmin()

2

In [132]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [133]:
arr.shape

(25,)

In [134]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [135]:
import numpy as np
arrey = np.arange(0,10)

In [136]:
arrey

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
arrey + arrey

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [138]:
arrey - arrey

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [139]:
arrey * arrey

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [140]:
arrey + 200

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209])

In [141]:
arrey - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])

In [142]:
arrey * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

This gives error because 0 is not divisible by 0

In [143]:
arrey / arrey

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [144]:
arrey ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [145]:
np.sqrt(arrey)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [146]:
np.exp(arrey)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [147]:
np.max(arrey)

9

In [148]:
arr.max()

24

In [149]:
np.sin(arrey)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [150]:
This gives error because log gives infinity error so it shows  - infinity

SyntaxError: invalid syntax (<ipython-input-150-20538bd1cd91>, line 1)

In [151]:
import numpy as np

In [152]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [153]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [154]:
np.ones(10)+4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [155]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [156]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [157]:
array = np.arange(9)

In [158]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [159]:
np.resize(array,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Another Way of doing this , Short mehtod

In [160]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [161]:
new = np.eye(3)
new

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [162]:
new == 0

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [163]:
np.random.rand(2)

array([0.44618417, 0.38335158])

In [164]:
np.random.randn(5,5)

array([[ 2.38066373, -0.7028373 , -1.20606466,  0.15946528, -0.49235413],
       [ 0.47803179,  1.38188098,  0.55848924, -0.2336835 ,  0.43360982],
       [-0.35330924,  2.20133334, -0.51662147,  0.43005647, -0.80973439],
       [ 1.20371889, -0.38301757,  1.17685091,  0.32050538, -0.7737412 ],
       [-0.15022823, -1.03200487, -0.55210657,  0.6941388 ,  1.91408427]])

In [165]:
np.zeros(100).reshape(10,10)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [166]:
np.arange(1,101).reshape(10,10)/10


array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [167]:
np.linspace(0,100,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [168]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [169]:
mat = np.arange(12,26)
mat

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [170]:
a = [4,9]
del_map = np.delete(mat, a)

In [171]:
del_map

array([12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, 25])

In [201]:
dell = del_map.reshape(3,4)
dell

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [202]:
dell[1][3]

20

In [209]:
abc = np.arange(2,13,5).reshape(3,1)
abc

array([[ 2],
       [ 7],
       [12]])

In [211]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

In [212]:
np.arange(16,26).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [213]:
np.sum(dell)

222

In [173]:
np.arange(10,26)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [174]:
np.arange(4)

array([0, 1, 2, 3])

In [175]:
np.arange(4).shape

(4,)

In [183]:
arr = np.arange(90)

In [186]:
arr.reshape(9,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [187]:
arr[:20]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [188]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [193]:
arr = arr.reshape(9,2,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [199]:
arr[4][1][4]

49

# 1D array indexing

In [235]:
axb = np.arange(10) ** 2
axb

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [236]:
axb[2]

4

In [237]:
axb[2:5]

array([ 4,  9, 16], dtype=int32)

In [238]:
axb[1:6:2]

array([ 1,  9, 25], dtype=int32)

In [239]:
axb[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0], dtype=int32)

In [240]:
axb[::-2]

array([81, 49, 25,  9,  1], dtype=int32)

In [241]:
axb[:4:2] 

array([0, 4], dtype=int32)

# 2D array

In [244]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [245]:
a[1]

array([3, 4, 5])

In [246]:
a[0][1]

1

In [247]:
a[1,1] #preferred

4

# Compare with Indexing of a list of lists

In [256]:
b = [[0, 1, 2], [3, 4, 5]]
b

[[0, 1, 2], [3, 4, 5]]

In [253]:
b[1]

array([3, 4, 5])

In [254]:
b[1][1]

4

In [258]:
# b[1,1]    gives error.. and does not work

# 2D array slicing

In [260]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [262]:
a[1, 2:4]

array([7, 8])

In [304]:
a[:,0:1]

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [303]:
a[:,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [302]:
a[:,2:3]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [301]:
a[:, 3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23]])

In [300]:
a[:, 4:5]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [291]:
a[0]

array([0, 1, 2, 3, 4])

In [292]:
a[1]

array([5, 6, 7, 8, 9])

In [294]:
a[2]

array([20, 21, 22, 23, 24])

In [295]:
a[3]

array([15, 16, 17, 18, 19])

In [296]:
a[4]

array([20, 21, 22, 23, 24])

In [305]:
a[:,:-1]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

# Fancy Indexing

In [306]:
a[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [311]:
a[::2, 2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [312]:
dell.std()

4.232808366400098

In [315]:
dell.sum(axis=0)

array([51, 54, 57, 60])

In [318]:
dell.sum(axis=1)

array([54, 74, 94])